version: "3"
services:
  api:
    restart: on-failure
    build:
      dockerfile: dev.dockerfile
      context: ./      
    volumes:
      - /var/www/vendor
      - ./:/var/www
    environment:
      # - DB_CONNECTION=mysql
      # - DB_HOST=database
      # - DB_PORT=3306
      # - DB_DATABASE=homestead
      # - DB_USERNAME=homestead
      # - DB_PASSWORD=secret
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8000:8000
  database:
    restart: always
    # image: mysql:latest
    image: mysql:5.6
    # command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./dbdata:/var/lib/mysql
    environment:
      # MYSQL_DATABASE: homestead
      # MYSQL_USER: homestead
      # MYSQL_ROOT_PASSWORD: secret
      # MYSQL_PASSWORD: secret
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 33061:3306
volumes:
  dbdata:
